apiVersion: v1
kind: Service
metadata:
  name: usermanagement
spec:
 type: LoadBalancer
 ports:
  - targetPort: 8090
    port: 8090
    nodePort: 30020
 selector:
  app: java-ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement
spec:
  selector:
    matchLabels:
      app: java-ms
  replicas: 2
  template:
    metadata:
      labels:
        app: java-ms
    spec:
      containers:
      - name: user-management-microservice
        imagePullPolicy: Always
        image: arjunbh/user-manangement:1.0.0
        ports:
        - containerPort: 8090 

