apiVersion: v1
kind: Service
metadata:
  name: data-retrieval
spec:
 type: LoadBalancer
 ports:
  - targetPort: 9002
    port: 9002
    nodePort: 30050
 selector:
  app: python
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-retrieval
spec:
  selector:
    matchLabels:
      app: python
  replicas: 3
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: data-retrieval
        imagePullPolicy: Always
        image: arjunbh/data-retrieval:1.0.0
        ports:
        - containerPort: 9002