apiVersion: v1
kind: Service
metadata:
  name: gatewayapi
spec:
 type: LoadBalancer
 ports:
  - targetPort: 8085
    port: 8085
    nodePort: 30008
 selector:
  app: java-ms
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayapi
spec:
  selector:
    matchLabels:
      app: java-ms
  replicas: 5
  template:
    metadata:
      labels:
        app: java-ms
    spec:
      containers:
      - name: gateway-api-microservice
        imagePullPolicy: Always
        image: arjunbh/gateway-api:latest
        ports:
        - containerPort: 8085
