apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gatewayapi-503
spec:
  hosts:
  - gatewayapi
  http:
  - route:
    - destination:
        host: gatewayapi
        subset: app-gatewayapi
    fault:
      abort:
        httpStatus: 503
        percent: 30