
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gatewayapi-timeout
spec:
  hosts:
  - gatewayapi
  http:
  - route:
    - destination:
        host: gatewayapi
    timeout: 1.000s