apiVersion: v1
kind: Service
metadata:
  name: sessionmanagement
spec:
 type: LoadBalancer
 ports:
  - targetPort: 4001
    port: 4001
    nodePort: 30040
 selector:
  app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sessionmanagement
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: sessionmanagement
        imagePullPolicy: Always
        image: arjunbh/session-management
        ports:
        - containerPort: 4001
      restartPolicy: Always
