apiVersion: v1
kind: Service
metadata:
  name: session-management
spec:
 type: LoadBalancer
 ports:
  - targetPort: 4001
    port: 4001
    nodePort: 30040
 selector:
  app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-management
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: session-management-microservice
        imagePullPolicy: Always
        image: arjunbh/session-management:1.0.0
        ports:
        - containerPort: 4001
      restartPolicy: Always