apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sessionmanagement-retry
spec:
  hosts:
  - sessionmanagement
  http:
  - route:
    - destination:
        host: sessionmanagement
    retries:
      attempts: 5
      perTryTimeout: 2s