apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
 type: LoadBalancer
 ports:
  - targetPort: 3000
    port: 3000
    nodePort: 30030
 selector:
  app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: front-end-microservice
        imagePullPolicy: Always
        image: arjunbh/front-end
        ports:
        - containerPort: 3000
      restartPolicy: Always
