apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: postanalysis
  name: postanalysis
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: postanalysis
    spec:
      containers:
      - image: arjunbh/post-analysis:latest
        name: post-analysis
        resources: {}
      restartPolicy: Always
status: {}
