apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: service-httpbin.default.svc.cluster.local
  namespace: defualt
spec:
  rules:
  - from:
    - source:
        principals:
        - default
    to:
    - operation:
        methods:
        - GET
  selector:
    matchLabels:
      app: httpbin
