apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: model-execution
  name: model-execution
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: model-execution
    spec:
      containers:
      - image: arjunbh/model-execution:latest
        name: model-execution
        resources: {}
      restartPolicy: Always
status: {}
