apiVersion: v1
kind: Service
metadata:
  name: model_execution
spec:
 type: LoadBalancer
 ports:
  - targetPort: 9010
    port: 9010
    nodePort: 30060
 selector:
  app: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model_execution
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: model_execution
        imagePullPolicy: Always
        image: arjunbh/model-execution:1.0.0
        ports:
        - containerPort: 9010
      restartPolicy: Always